config/routes.rb
Rails.application.routes.draw do
  resources :runs do
    member do
      patch "end"
    end
  end
  resources :tumblers

  resources :users do
    resources :tumblers
    resources :runs
  end
  resource :registration, only: %i[new create]
  resource :session
  resources :passwords, param: :token
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  has_many :tumblers
  has_many :runs, through: :tumblers

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :title, :body, :before_image ])
    end
end

app/views/users/show.html.erb
<h1 class="mt-2 mb-0"><%= @user.email_address %></h1>

<h2>Current Runs</h2>
<ul>
    <li>
        <%= link_to "New Run", new_run_path %>
    </li>
    <% @user.runs.where(ended_at: nil).each do |run| %>
        <li>
            <%= link_to(run) do %>
                <% label = (run.started_at + run.duration.days).past? ? "Ended" : "Ends in" %>
                <%= run.stage %>: <%= label %> <%= distance_of_time_in_words(run.started_at, run.started_at + run.duration.days) %> from now 
                <%= form_with model: run, url: end_run_path(run) do |form| %>
                    <%= form.submit "End Now" %>
                <% end %>
            <% end %>
        </li>
    <% end %>
</ul>

<h2>Ended Runs</h2>
<ul>
    <% @user.runs.where.not(ended_at: nil).each do |run| %>
        <li>
            <%= link_to(run) do %>
                <%= run.stage %>: Ended <%= time_ago_in_words(run.ended_at) %> ago
            <% end %>
        </li>
    <% end %>
</ul>