config/routes.rb
Rails.application.routes.draw do
  resources :runs do
    member do
      patch "end"
    end
  end
  resources :tumblers

  resources :users do
    resources :tumblers
    resources :runs
  end
  resource :registration, only: %i[new create]
  resource :session
  resources :passwords, param: :token
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/tumbler.rb
class Tumbler < ApplicationRecord
  belongs_to :user
  has_many :runs
end

app/controllers/tumblers_controller.rb
class TumblersController < ApplicationController
  before_action :set_tumbler, only: %i[ show edit update destroy ]

  # GET /tumblers or /tumblers.json
  def index
    @tumblers = Current.user.tumblers.all
  end

  # GET /tumblers/1 or /tumblers/1.json
  def show
  end

  # GET /tumblers/new
  def new
    @tumbler = Current.user.tumblers.new
  end

  # GET /tumblers/1/edit
  def edit
  end

  # POST /tumblers or /tumblers.json
  def create
    @tumbler = Current.user.tumblers.new(tumbler_params)

    respond_to do |format|
      if @tumbler.save
        format.html { redirect_to @tumbler, notice: "Tumbler was successfully created." }
        format.json { render :show, status: :created, location: @tumbler }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tumbler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tumblers/1 or /tumblers/1.json
  def update
    respond_to do |format|
      if @tumbler.update(tumbler_params)
        format.html { redirect_to @tumbler, notice: "Tumbler was successfully updated." }
        format.json { render :show, status: :ok, location: @tumbler }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tumbler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tumblers/1 or /tumblers/1.json
  def destroy
    @tumbler.destroy!

    respond_to do |format|
      format.html { redirect_to tumblers_path, status: :see_other, notice: "Tumbler was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tumbler
      @tumbler = Tumbler.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def tumbler_params
      params.expect(tumbler: [ :name, :brand, :model ])
    end
end

app/helpers/tumblers_helper.rb
module TumblersHelper
end

app/views/tumblers/_form.html.erb
<%= form_with(model: tumbler, class: "contents") do |form| %>
  <% if tumbler.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(tumbler.errors.count, "error") %> prohibited this tumbler from being saved:</h2>

      <ul class="list-disc ml-6">
        <% tumbler.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": tumbler.errors[:name].none?, "border-red-400 focus:outline-red-600": tumbler.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": tumbler.errors[:brand].none?, "border-red-400 focus:outline-red-600": tumbler.errors[:brand].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :model %>
    <%= form.text_field :model, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": tumbler.errors[:model].none?, "border-red-400 focus:outline-red-600": tumbler.errors[:model].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tumblers/_tumbler.html.erb
<div id="<%= dom_id tumbler %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= tumbler.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Brand:</strong>
    <%= tumbler.brand %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Model:</strong>
    <%= tumbler.model %>
  </div>
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= tumbler.user_id %>
  </div>
</div>

app/views/tumblers/edit.html.erb
<% content_for :title, "Editing tumbler" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing tumbler</h1>

  <%= render "form", tumbler: @tumbler %>

  <%= link_to "Show this tumbler", @tumbler, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to tumblers", tumblers_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/tumblers/index.html.erb
<% content_for :title, "Tumblers" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tumblers</h1>
    <%= link_to "New tumbler", new_tumbler_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="tumblers" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @tumblers.any? %>
      <% @tumblers.each do |tumbler| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render tumbler %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", tumbler, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_tumbler_path(tumbler), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", tumbler, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No tumblers found.</p>
    <% end %>
  </div>
</div>

app/views/tumblers/new.html.erb
<% content_for :title, "New tumbler" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New tumbler</h1>

  <%= render "form", tumbler: @tumbler %>

  <%= link_to "Back to tumblers", tumblers_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/tumblers/show.html.erb
<% content_for :title, "Showing tumbler" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing tumbler</h1>

  <%= render @tumbler %>

  <%= link_to "Edit this tumbler", edit_tumbler_path(@tumbler), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to tumblers", tumblers_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this tumbler", @tumbler, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>