config/routes.rb
Rails.application.routes.draw do
  resources :runs do
    member do
      patch "end"
    end
  end
  resources :tumblers

  resources :users do
    resources :tumblers
    resources :runs
  end
  resource :registration, only: %i[new create]
  resource :session
  resources :passwords, param: :token
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :tumbler
  has_many_attached :images

  validates :duration, presence: true
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: %i[ show edit update destroy end ]

  # GET /runs or /runs.json
  def index
    @runs = Run.all
  end

  # GET /runs/1 or /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  def end
    @run.update(ended_at: Time.current)
    redirect_to :back, notice: "Run was successfully ended."
  end

  # POST /runs or /runs.json
  def create
    @run = Run.new(run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: "Run was successfully created." }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1 or /runs/1.json
  def update
    if params[:run] && params[:run][:started_at]
      params[:run][:started_at] = Time.now.utc
    end

    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: "Run was successfully updated." }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1 or /runs/1.json
  def destroy
    @run.destroy!

    respond_to do |format|
      format.html { redirect_to runs_path, status: :see_other, notice: "Run was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def run_params
      params.expect(run: [ :started_at, :ended_at, :duration, :stage, :notes, :tumbler_id, images: [] ])
    end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.erb
<%= form_with(model: run, class: "contents") do |form| %>
  <% if run.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul class="list-disc ml-6">
        <% run.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :duration %>
    <%= form.number_field :duration, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": run.errors[:duration].none?, "border-red-400 focus:outline-red-600": run.errors[:duration].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :stage %>
    <%= form.text_field :stage, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": run.errors[:stage].none?, "border-red-400 focus:outline-red-600": run.errors[:stage].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.textarea :notes, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": run.errors[:notes].none?, "border-red-400 focus:outline-red-600": run.errors[:notes].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :tumbler_id %>

    <%= form.select :tumbler_id, Current.user.tumblers.collect { |t| [ t.name, t.id ] } %>
  </div>

  <% @run.images.each do |image| %>
    <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
  <% end %> 

  <div class="my-5">
    <%= form.file_field(:images, multiple: true) %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/runs/_run.html.erb
<div id="<%= dom_id run %>" class="">
  <div>
    <% if run.started_at %>
      <strong class="">Started:</strong>
      <%= time_ago_in_words run.started_at %> ago at <%= local_time(run.started_at) %>
    <% else %>
      Run not yet started: 
      <%= form_for run do |f| -%>
        <%= f.hidden_field :started_at, value: 1 %>
        <%= f.submit "Start run" %>
      <% end -%>
    <% end %>
  </div>
  <div>
    <strong class="">Ends in</strong>
    <% if run.started_at && run.duration %>
      <%= distance_of_time_in_words Time.now.utc, run.started_at + run.duration.days %> at <%= local_time(run.started_at + run.duration.days) %>
    <% end %>
  </div>
  <div>
    <strong class="">Duration:</strong>
    <%= run.duration %> days
  </div>
  <div>
    <strong class="">Stage:</strong>
    <%= run.stage %>
  </div>
  <div>
    <strong class="">Notes:</strong>
    <%= run.notes %>
  </div>
  <div>
    <strong class="">Tumbler:</strong>
    <%= run.tumbler.name %>
  </div>
</div>

app/views/runs/edit.html.erb
<% content_for :title, "Editing run" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing run</h1>

  <%= render "form", run: @run %>

  <%= link_to "Show this run", @run, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to runs", runs_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/runs/index.html.erb
<% content_for :title, "Runs" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Runs</h1>
    <%= link_to "New run", new_run_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="runs" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @runs.any? %>
      <% @runs.each do |run| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render run %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", run, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_run_path(run), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", run, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No runs found.</p>
    <% end %>
  </div>
</div>

app/views/runs/new.html.erb
<% content_for :title, "New run" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New run</h1>

  <%= render "form", run: @run %>

  <%= link_to "Back to runs", runs_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/runs/show.html.erb
<% content_for :title, "Showing run" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Run <%= @run.id %></h1>

  <%= render @run %>

  <% for image in @run.images do %>
    <%= image_tag(image, class: "img-fluid") %>
  <% end %>

  <%= link_to "Edit this run", edit_run_path(@run), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to runs", runs_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  
  <%= button_to "Delete", @run, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "btn btn-danger", data: { turbo_confirm: "Are you sure?" } %>
</div>